import Organizer from '../models/Organizer.js';
import PasswordResetRequest from '../models/PasswordResetRequest.js';

// Route: GET /api/admin/organizers
//Description:Get all organizers

export const getOrganizers=async (requestAnimationFrame,resizeBy,next)=>{
    try{
        //return all organizers without their passwords
        const organizers= await Organizer.find({}).select('-password');

    }catch(error){
        next (error);
    }
};

//Route: POST /api/admin/organizers
//Description:Add new organizer

export const createOrganizer =async (req,res,next) =>{
    try{
        const { organizerName,category,description,contactEmail}=req.body;

        const organizerExists=await Organizer.findOne({ contactEmail});

        if(organizerExists){
            res.status(400);
            throw new Error('Organizer with thi email already exists');
        }


        const nameExists= await Organizer.findOne({organizerName});

        if(nameExists){
            res.status(400);
            throw new Error('Organizer with this name already exists');
        }

        // Auto-generate a random secure password for the new organizer
    
        // In a real application, you would email this to the organizer.
    
        // Here, we just return it in the response for the Admin to share.

        const generatedPassword=Math.random().toString(36).slice(-8) + Math.random().toString(36).slice(-8);

        //create the organizer in the database
        const organizer=await Organizer.create({
            organizerName,
            category,
            description,
            contactEmail,
            password: generatedPassword,
        });

        if(organizer){
            res.status(201).json({
                //this is the id which is automatically created when we make an entry is mongodb and is automatically generated by mongodb.
                _id:organizer._id,
                organizerName:organizer.organizerName,
                category:organizer.category,
                contactEmail:organizer.contactEmail,
                initialPassword:generatedPassword,
            });
        }else{
            res.status(400);
            throw new Error('Invalid organizer data');
        }
    }catch(error){
        next(error);
    }
    
};

//Route: DELETE /api/admin/organizers/:id
//Description:Delete an organizer

export const deleteOrganizer=async(req,res,next)=>{
    try{
        const organizer= await Organizer.findById(req.params.id);
        if(organizer){
            await Organizer.deleteOne({_id:organizer._id});
            res.json({message:'Organizer removed successfully'});
        }else{
            res.status(404);
            throw new Error('Organizer not found');
        }
    }catch(error){
        next(error);
    }
};


//Route:  GET /api/admin/password-request
//Description: get all the password reset requestPasswordReset

export const getPasswordRequests=async(req,res,next)=>{
    try{
    // Populate the organizer details so the admin sees who is requesting
    const requests=await PasswordResetRequest.find({}).populate('organizer','organizerName contactEmail category').sort({createdAt:-1});

    res.json(requests);
    }catch(error){
        next(error);
    }

};

//Route: PUT /api/admin/password-requests/:id
//Description:Approve or reject a password reset request

export const updatePasswordRequestStatus=async(req,res,next)=>{
    try{
        const{status}=req.body;
        const request=await PasswordResetRequest.findById(req.params.id).populate('organizer');

        if(!request){
            res.status(404);
            throw new Error('Request not found')
        }

        if(request.status!=='Pending'){
            res.status(400);
            throw new Error('Request already processed');

        }
        if(status==='Approved'){
            // Auto-generate new password
            const newPassword = Math.random().toString(36).slice(-8) + Math.random().toString(36).slice(-8);

            //Update Organizers Password
            const organizer=await Organizer.findById(request.organizer._id);
            organizer.password=newPassword;
            await organizer.save();

            //Update the request status and temp store the new password so admin can see it.
            request.status='Approved';
            request.newPasswordGenerated=newPassword;

            await request.save();

            res.json({ message: 'Request approved, password has been reset.', request });

        }
        else if(status==='Rejected'){
            request.stauts='Rejected'
            await request.save();
            res.json({ message: 'Request rejected.', request });
        }
        else{
            res.status(400);
            throw new Error('Invalid status');
        }

    }catch(error){
        next(error);
    }
};